import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

import { cycleDailySupport } from '@/features/cycle/data/cycle-daily-support';
import { disclaimerMessages } from '@/features/disclaimer/presentation/disclaimer-messages';
import { pregnancyWeeklyContent } from '@/features/pregnancy/data/pregnancy-weekly-content';

/**
 * Builds `ENGLISH_REVIEW.md`, the file a native-English reviewer is handed.
 *
 * ## Why a test rather than a script
 *
 * The file has to be a real file - somebody is going to email it to a reviewer
 * who has no checkout and no Node. But a copy of the app's text in a second
 * place is a copy that goes stale, and a reviewer reading last month's wording
 * is worse than no reviewer: they sign off on strings the app no longer shows.
 *
 * So it is generated from the catalogues and checked in, and this test fails
 * when the two disagree. Regenerate with:
 *
 * ```
 * UPDATE_ENGLISH_REVIEW=1 npx jest english-review-package
 * ```
 *
 * The same mechanism as a snapshot test, written out longhand because the
 * artefact is meant to be read by a person who is not looking at this
 * repository.
 *
 * ## What goes in it
 *
 * The disclaimer, the four cycle phases and all forty pregnancy weeks: Turkish
 * and English side by side, each entry with its own citations, each section with
 * what to check for. Nothing else - the interface strings are not in here. A
 * reviewer given 1,400 strings reads none of them; these are the ones where
 * being wrong matters, and they are the ones written from medical sources.
 */

const OUTPUT = join(__dirname, '..', '..', 'ENGLISH_REVIEW.md');

/** A fenced block, so a reviewer sees the string and not Markdown's reading of it. */
function quote(value: string): string {
  return ['```text', value, '```'].join('\n');
}

/** One Turkish/English pair, labelled. */
function pair(tr: string, en: string): string {
  return ['**Turkish**', '', quote(tr), '', '**English**', '', quote(en), ''].join('\n');
}

function sourceList(sources: readonly { readonly name: string; readonly url: string }[]): string {
  return sources.map((source) => `- ${source.name}  \n  <${source.url}>`).join('\n');
}

const HEADER = `# English copy review

The app's health content and its disclaimer, in Turkish and English, for review
by a native English speaker.

**Generated from the source catalogues** - do not edit this file by hand. It is
rebuilt and checked by \`src/__tests__/english-review-package.test.ts\`, so an
edit here is overwritten and a change in the app shows up here as a failing
test. Send corrections as comments or as a marked-up copy; they will be applied
to the catalogues.

## What to check for

The English was written from the cited sources rather than translated out of the
Turkish, so this is not a check that the two match word for word. It is a check
that they make **the same claim with the same strength**. Two failure directions,
and the second is the dangerous one:

1. **A hedge that weakened.** The NHS and Cleveland Clinic pages hedge
   constantly - "may", "might", "can", "usually", "some people". A hedge is easy
   to lose when a sentence is rewritten to read better, and the result is the app
   stating as fact something its source would not. If an English sentence sounds
   more certain than its Turkish counterpart, say so.
2. **A claim that strengthened.** The same thing one step further: an English
   sentence that asserts something the Turkish only suggests, or that adds a
   detail the Turkish does not carry. Anything in the English with no counterpart
   in the Turkish is worth flagging even if it reads well.

Also worth flagging:

- **Mood and feeling labels that read as statements.** Every one should be a
  "may", "might", "can" or "possible". A label that tells somebody how they feel
  is wrong however accurate it is on average.
- **Instructions the sources do not give.** Only two entries are meant to
  instruct rather than describe - weeks 31 and 40, which say to contact a doctor
  or midwife. An instruction anywhere else is a mistake.
- **Numbers and measurements.** The figures must be identical in both languages;
  they are the sources' own. Only the decimal mark differs - Turkish writes
  "25,6 cm" and English "25.6 cm", which is convention and not a discrepancy.
  The lengths also change basis between weeks 19 and 21 because the NHS pages do
  (head-to-bottom, then head-to-toe, then head-to-heel); that is deliberate and
  is not an error.
- **Anything that reads like a diagnosis**, or like the app telling somebody what
  is normal. It should never do either.
- **Plain unnaturalness.** Turkish-shaped English, a word that is not wrong but
  is not what a British or American reader would say. Flag it; naturalness is
  half of why this review exists.

Citations are deliberately **not translated**. They are English-language health
bodies and their page titles are what somebody would search for, so a translated
name would make a claim harder to check - which is the one thing a citation is
for.

The emergency line is deliberately **not the same** in the two languages: the
Turkish says 112 and the English says "contact your local emergency services"
and names no number. A language is not a country. This is intentional and is not
a translation that drifted.
`;

function disclaimerSection(): string {
  const { tr, en } = disclaimerMessages;

  const points = tr.disclaimerPoints
    .map((point, index) => {
      const heading = ['Not medical advice', 'Not contraception', 'Emergency'][index];

      return [`#### Point ${index + 1} - ${heading}`, '', pair(point, en.disclaimerPoints[index])].join(
        '\n'
      );
    })
    .join('\n');

  const paragraphs = tr.aboutImportantParagraphs
    .map((paragraph, index) =>
      [
        `#### Paragraph ${index + 1}`,
        '',
        pair(paragraph, en.aboutImportantParagraphs[index]),
      ].join('\n')
    )
    .join('\n');

  return [
    '## 1. The disclaimer',
    '',
    'The highest-stakes copy in the app. The wording is fixed on purpose: a',
    'screen that cannot fit these sentences is a screen that needs changing, not',
    'a reason to shorten them. Read these first and read them hardest.',
    '',
    '### The onboarding screen, shown once before anything else',
    '',
    '#### Title',
    '',
    pair(tr.disclaimerTitle, en.disclaimerTitle),
    '#### Introduction',
    '',
    pair(tr.disclaimerIntro, en.disclaimerIntro),
    '### The three points',
    '',
    'A list rather than a paragraph because these are the points somebody has to',
    'be able to find again, and the middle one - that this is not contraception -',
    'is the one a wall of text would swallow.',
    '',
    points,
    '### The long form, on the About screen',
    '',
    paragraphs,
    '### The footer under every piece of health content',
    '',
    'One line, shown under the daily cycle note and under every pregnancy week.',
    '',
    pair(tr.contentDisclaimerFooter, en.contentDisclaimerFooter),
  ].join('\n');
}

function cycleSection(): string {
  const entries = cycleDailySupport.tr.map((trPhase, index) => {
    const enPhase = cycleDailySupport.en[index];

    const moods =
      trPhase.moodLabels === undefined || enPhase.moodLabels === undefined
        ? [
            '**Mood labels:** none, deliberately.',
            '',
            trPhase.phase === 'ovulatory'
              ? 'The cited pages say nothing about mood at ovulation. The popular' +
                ' "energetic, cheerful ovulation" label has nothing behind it in these' +
                ' sources, so the app says nothing rather than repeating it.'
              : 'The cited pages do not support mood labels for this phase.',
            '',
          ].join('\n')
        : [
            '**Mood labels**',
            '',
            '| Turkish | English |',
            '| --- | --- |',
            ...trPhase.moodLabels.map(
              (mood, moodIndex) => `| ${mood} | ${enPhase.moodLabels?.[moodIndex] ?? ''} |`
            ),
            '',
            'Each of these should read as a possibility, not a statement.',
            '',
          ].join('\n');

    return [
      `### ${index + 1}. The ${trPhase.phase} phase`,
      '',
      '**Support message**',
      '',
      pair(trPhase.supportMessage, enPhase.supportMessage),
      moods,
      '**Sources**',
      '',
      sourceList(trPhase.sources),
      '',
    ].join('\n');
  });

  return [
    '## 2. The four cycle phases',
    '',
    'Shown on the home screen with the disclaimer footer beneath it. One message',
    'per phase, plus mood labels where the sources support them.',
    '',
    ...entries,
  ].join('\n');
}

function pregnancySection(): string {
  const entries = pregnancyWeeklyContent.tr.map((trWeek, index) => {
    const enWeek = pregnancyWeeklyContent.en[index];

    const size =
      trWeek.size === undefined || enWeek.size === undefined
        ? [
            '**Size:** none for this week, deliberately. Gestational age is counted',
            'from the last menstrual period, so there is nothing yet whose size is',
            'worth stating.',
            '',
          ].join('\n')
        : [
            '**Size**',
            '',
            `| | Turkish | English |`,
            `| --- | --- | --- |`,
            `| Measurement | ${trWeek.size.label} | ${enWeek.size.label} |`,
            `| Compared to | ${trWeek.size.comparison} | ${enWeek.size.comparison} |`,
            '',
            'The measurement must be the same figure in both - only the decimal mark',
            'changes, a comma in Turkish and a point in English. The comparison is an',
            'everyday object and may legitimately differ if the Turkish one would not',
            'mean anything to an English reader; flag it if it would not.',
            '',
          ].join('\n');

    const features = [
      '**What is developing**',
      '',
      '| Turkish | English |',
      '| --- | --- |',
      ...trWeek.developingFeatures.map(
        (feature, featureIndex) =>
          `| ${feature} | ${enWeek.developingFeatures[featureIndex] ?? ''} |`
      ),
      '',
    ].join('\n');

    return [
      `### Week ${trWeek.week}`,
      '',
      '**Development summary**',
      '',
      pair(trWeek.developmentSummary, enWeek.developmentSummary),
      size,
      features,
      '**Sources**',
      '',
      sourceList(trWeek.sources),
      '',
    ].join('\n');
  });

  return [
    '## 3. The forty pregnancy weeks',
    '',
    'Shown one week at a time on the home screen in pregnancy mode, each with the',
    'disclaimer footer beneath it. The NHS week-by-week guide is the primary',
    'source from week 4 on; Cleveland Clinic is cited alongside as corroboration.',
    'Where the two put a milestone in different weeks, the week here is the NHS',
    'one.',
    '',
    '**Weeks 31 and 40 are the only two entries meant to instruct** - they say to',
    'contact a doctor or midwife. Everywhere else the content describes and does',
    'not advise.',
    '',
    ...entries,
  ].join('\n');
}

function buildReview(): string {
  return [
    HEADER,
    disclaimerSection(),
    cycleSection(),
    pregnancySection(),
    '## Returning this',
    '',
    'Mark up anything that reads unnaturally, anything where the English is more',
    'or less certain than the Turkish, and anything that sounds like advice or a',
    'diagnosis. A sentence that is fine can be left alone - silence on an entry',
    'is taken to mean it passed.',
    '',
  ].join('\n\n');
}

describe('the English review package', () => {
  it('matches the catalogues it was generated from', () => {
    const built = buildReview();

    if (process.env.UPDATE_ENGLISH_REVIEW === '1') {
      writeFileSync(OUTPUT, built, 'utf8');
    }

    const committed = readFileSync(OUTPUT, 'utf8');

    // Compared with newlines normalised: the file is checked out with CRLF on
    // Windows and LF in CI, and a line-ending difference is not a copy change.
    expect(committed.replace(/\r\n/g, '\n')).toBe(built.replace(/\r\n/g, '\n'));
  });

  it('carries every week and every phase', () => {
    // A generator that silently emitted half the weeks would still match a
    // committed file generated by the same bug.
    const built = buildReview();

    expect(pregnancyWeeklyContent.tr).toHaveLength(40);
    expect(cycleDailySupport.tr).toHaveLength(4);

    for (const week of pregnancyWeeklyContent.tr) {
      expect([week.week, built.includes(`### Week ${week.week}\n`)]).toEqual([week.week, true]);
    }

    for (const phase of cycleDailySupport.tr) {
      expect([phase.phase, built.includes(`phase`)]).toEqual([phase.phase, true]);
    }
  });

  it('shows both halves of the emergency line, which is the one deliberate difference', () => {
    const built = buildReview();

    expect(built).toContain('112');
    expect(built).toContain('contact your local emergency services');
  });
});
